/**
 * 
 */
package com.sysc3303.project.elevator;

import java.io.Serializable;

/**
 * Represents the response object generated by the elevator
 * 
 * @author Group 9
 *
 */
public class ElevatorResponse implements Serializable {
	private final String message;

	/**
	 * Constructor
	 * 
	 * @param message The message of the response
	 */
	public ElevatorResponse(String message) {
		this.message = message;
	}

	/**
	 * @return the message of the response
	 */
	public String getMessage() {
		return message;
	}

	/**
	 * The String representation of the object
	 */
	@Override
	public String toString() {
		return message;
	}
}
