/**
 * 
 */
package com.sysc3303.project;


/**
 * Represents the response object generated by the elevator
 * @author Group 9
 *
 */
public class ElevatorResponse {
	private final Floor floor; //The floor object to send the response to
	private final String message;
	
	/**
	 * Constructor
	 * @param floor The Floor object that is being sent the response
	 * @param message The message of the response
	 */
	public ElevatorResponse(Floor floor, String message) {
		if (floor == null) {
			throw new IllegalArgumentException("The Floor object cannot be null");
		}
		this.floor = floor;
		this.message = message;
	}
	
	/**
	 * @return the Floor object to send the response to
	 */
	public Floor getFloor() {
		return floor;
	}
	
	/**
	 * @return the message of the response
	 */
	public String getMessage() {
		return message;
	}
	
	
	/**
	 * The String representation of the object
	 */
	@Override
	public String toString() {
		return message;
	}
}
